[phases.setup]
nixPkgs = ["python311", "python311Packages.pip"]

[phases.install]
cmds = ["python -m pip install -r requirements.txt"]

[phases.build]
cmds = ["python -m pip install -r requirements.txt"]

[start]
cmd = "cd backend && python -m gunicorn wsgi:app --bind 0.0.0.0:$PORT --workers 2"
